Repository skkuse/2023spring_41class_team3, pull requests merged in 2023-05, with the labels that each got.

#8 Http Request Interceptor 구현
  server/package.json
  server/src/interceptor/http.interceptor.ts
  server/src/main.ts
  server/yarn.lock
Labels: Back, Feature

#10 http exception filter 구현
  server/src/constant/exception-message.constant.ts
  server/src/constant/index.ts
  server/src/filter/http.filter.ts
  server/src/interceptor/http.interceptor.ts
  server/src/main.ts
  server/tsconfig.json
  server/tsconfig.path.json
Labels: Back, Feature

#12 mongoDB, mongoose 설정
  server/.gitignore
  server/docker-compose.yml
  server/package.json
  server/src/app.module.ts
  server/src/cat/cat.controller.spec.ts
  server/src/cat/cat.controller.ts
  server/src/cat/cat.module.ts
  server/src/cat/cat.service.spec.ts
  server/src/cat/cat.service.ts
  server/src/cat/dto/create-cat.dto.ts
  server/src/cat/dto/update-cat.dto.ts
  server/src/cat/entities/cat.entity.ts
  server/src/cat/mongo.cat.repository.ts
  server/src/config/env.config.ts
  server/src/config/index.ts
  server/src/config/mongoose.config.ts
  server/tsconfig.json
  server/tsconfig.path.json
  server/yarn.lock
Labels: Back, Env, Feature

#14 GitHub oauth login 구현
  client/.eslintrc.js
  client/package.json
  client/src/App.js
  client/src/api/auth.js
  client/src/components/Landing/LoginContainer.jsx
  client/src/components/LoginButton.jsx
  client/src/pages/LandingPages/LandingPage.jsx
  client/src/setupProxy.js
  client/yarn.lock
  server/.gitignore
  server/package.json
  server/src/app.module.ts
  server/src/cat/cat.controller.spec.ts
  server/src/cat/cat.controller.ts
  server/src/cat/cat.module.ts
  server/src/cat/cat.service.spec.ts
  server/src/cat/cat.service.ts
  server/src/cat/dto/create-cat.dto.ts
  server/src/cat/dto/update-cat.dto.ts
  server/src/cat/entities/cat.entity.ts
  server/src/cat/mongo.cat.repository.ts
  server/src/config/env.config.ts
  server/src/config/mongoose.config.ts
  server/src/constant/auth.constant.ts
  server/src/constant/env.constant.ts
  server/src/constant/exception-message.constant.ts
  server/src/constant/index.ts
  server/src/filter/http.filter.ts
  server/src/filter/mongoose.filter.ts
  server/src/main.ts
  server/src/types/auth.type.ts
  server/src/types/index.ts
  server/src/user/auth/controller/auth.controller.ts
  server/src/user/auth/guard/jwt.guard.ts
  server/src/user/auth/repository/auth.repository.ts
  server/src/user/auth/service/auth.service.ts
  server/src/user/auth/strategy/jwt.strategy.ts
  server/src/user/dto/oauth-url.dto.ts
  server/src/user/entities/user.entity.ts
  server/src/user/oauth/oauth.github.ts
  server/src/user/oauth/oauth.interface.ts
  server/src/user/user.module.ts
  server/tsconfig.path.json
  server/yarn.lock
Labels: Back, Feature

#21 로그인 유지 기능 구현
  client/src/api/auth.js
  client/src/components/LoginButton.jsx
  client/src/hooks/auth.js
  client/src/pages/LandingPages/LandingPage.jsx
  server/src/user/auth/controller/auth.controller.ts
Labels: Front, Back, Feature

#26 Feature/feedback page
  client/.eslintrc.js
  client/package.json
  client/src/App.js
  client/src/actions/setResults.js
  client/src/assets/images/logos/OpenAI-svg.js
  client/src/components/Result/CodeBox.jsx
  client/src/components/Result/DialogContent.jsx
  client/src/components/Result/ResultAnalysis.jsx
  client/src/components/Result/ResultContent.jsx
  client/src/components/Result/ResultFeedback.jsx
  client/src/components/Result/ResultImproved.jsx
  client/src/components/Result/ResultReadability.jsx
  client/src/components/Result/ResultTimeComplex.jsx
  client/src/components/Result/SidebarContainer.jsx
  client/src/components/common/Footer.jsx
  client/src/components/common/Header.jsx
  client/src/index.js
  client/src/pages/LandingPages/LandingPage.jsx
  client/src/pages/ResultPages/ResultPage.jsx
  client/src/reducers/problemNoReducer.js
  client/src/reducers/resultTypeReducer.js
  client/src/reducers/rootReducer.js
  client/src/store/store.js
  client/yarn.lock
Labels: Front, Feature

#30 25 cicd 및 배포 deploy
  .github/workflows/client-deploy.yml
  .github/workflows/server-deploy.yml
  client/appspec.yml
  server/docker-compose.yml
  server/scripts/server_setup.sh
  server/scripts/start_server.sh
  server/scripts/start_services.sh
  server/src/appspec.yml
  server/src/config/env.config.ts
  server/src/constant/env.constant.ts
  server/src/user/oauth/oauth.github.ts
Labels: Feature, Build

#31 fix: (back) appspec.yml의 위치를 root로 수정
  server/appspec.yml
Labels: Back, Build

#29 Feature/main page
  client/.eslintrc.js
  client/package.json
  client/src/App.js
  client/src/assets/images/imagesource/MainPage_CodingTestButton.png
  client/src/assets/images/imagesource/MainPage_PSModeButton.png
  client/src/assets/images/imagesource/MainPage_StartCodingTest.png
  client/src/assets/images/imagesource/MainPage_background.png
  client/src/assets/images/imagesource/PSSelectPage_background.png
  client/src/assets/images/imagesource/PSSelectPage_searchbuttonimage.png
  client/src/components/Landing/IntroContainerFirst.jsx
  client/src/components/Landing/IntroContainerSecond.jsx
  client/src/components/Main/CodingTestModal.jsx
  client/src/components/Main/MainContainerFirst.jsx
  client/src/components/PSSelect/PSListContainer.jsx
  client/src/components/PSSelect/SearchBoxContainer.jsx
  client/src/components/layout/Header2.jsx
  client/src/pages/MainPages/MainPage.jsx
  client/yarn.lock
  package.json
Labels: Front, Feature

#33 feat: (front) loading component 구현 및 적용
  client/package.json
  client/src/components/common/spinner.jsx
  client/src/pages/LandingPages/LandingPage.jsx
  client/yarn.lock
Labels: Front, Feature
